# Generated by Django 6.0.2 on 2026-03-03 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя игрока')),
                ('team_name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('color', models.CharField(default='#ef4444', max_length=20)),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_double_round', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField(default=1, verbose_name='Номер тура')),
                ('home_score', models.IntegerField(blank=True, null=True, verbose_name='Голы хозяина')),
                ('away_score', models.IntegerField(blank=True, null=True, verbose_name='Голы гостя')),
                ('is_played', models.BooleanField(default=False, verbose_name='Сыгран')),
                ('is_home', models.BooleanField(default=True, verbose_name='Первый матч дома')),
                ('away_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournament.player', verbose_name='Гость')),
                ('home_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournament.player', verbose_name='Хозяин')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['round_num', 'id'],
            },
        ),
    ]
