# Generated by Django 6.0.2 on 2026-03-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки к матчу'),
        ),
        migrations.AddField(
            model_name='match',
            name='station',
            field=models.CharField(blank=True, max_length=100, verbose_name='Корт / станция'),
        ),
        migrations.AddField(
            model_name='player',
            name='seed',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Посев'),
        ),
        migrations.AddField(
            model_name='settings',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание / объявления'),
        ),
        migrations.AddField(
            model_name='settings',
            name='name',
            field=models.CharField(default='FC26 TOURNAMENT', max_length=200, verbose_name='Название турнира'),
        ),
    ]
