# Generated by Django 6.0.2 on 2026-03-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_settings_name_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL логотипа'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя игрока'),
        ),
    ]
