# Generated by Django 6.0.2 on 2026-03-03 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_player_logo_and_name_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_matches', to='tournament.match', verbose_name='Следующий матч для победителя'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_slot',
            field=models.CharField(blank=True, help_text='В какую ячейку следующего матча записать победителя', max_length=10, verbose_name='Слот победителя (home/away)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='has_group_stage',
            field=models.BooleanField(default=False, verbose_name='С групповым этапом'),
        ),
        migrations.AddField(
            model_name='settings',
            name='tournament_type',
            field=models.CharField(choices=[('round_robin', 'Круговой'), ('bracket', 'Олимпийская система (брекеты)')], default='round_robin', max_length=20, verbose_name='Тип турнира'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournament.player', verbose_name='Гость'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournament.player', verbose_name='Хозяин'),
        ),
        migrations.AlterField(
            model_name='match',
            name='round_num',
            field=models.IntegerField(default=1, verbose_name='Номер тура / раунда'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_double_round',
            field=models.BooleanField(default=False, verbose_name='Два круга'),
        ),
    ]
