# Generated by Django 6.0.2 on 2026-03-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_populate_star_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='rating',
            field=models.IntegerField(verbose_name='Рейтинг (числовой)'),
        ),
        migrations.AlterField(
            model_name='tournamentteamsettings',
            name='max_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Макс. рейтинг (числовой)'),
        ),
        migrations.AlterField(
            model_name='tournamentteamsettings',
            name='min_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мин. рейтинг (числовой)'),
        ),
    ]
