# Generated by Django 6.0.2 on 2026-03-03 11:32

import django.db.models.deletion
import tournament.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_game_profiles_and_stats'),
        ('tournament', '0015_alter_team_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_players', to='accounts.gameprofile', verbose_name='Игровой профиль'),
        ),
        migrations.CreateModel(
            name='MatchHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=tournament.models._default_highlight_slug, max_length=32, unique=True, verbose_name='Код ссылки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_highlights', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='tournament.match', verbose_name='Матч')),
            ],
            options={
                'verbose_name': 'Публичная ссылка на матч',
                'verbose_name_plural': 'Публичные ссылки на матчи',
            },
        ),
        migrations.CreateModel(
            name='TournamentHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=tournament.models._default_highlight_slug, max_length=32, unique=True, verbose_name='Код ссылки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_highlights', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='tournament.settings', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Публичная страница турнира',
                'verbose_name_plural': 'Публичные страницы турниров',
            },
        ),
    ]
