# Generated by Django 5.2.9 on 2026-03-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_player_game_profile_and_highlights'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_global_enabled', models.BooleanField(default=True, verbose_name='Реклама включена')),
                ('adsense_enabled', models.BooleanField(default=False, verbose_name='Включить Google AdSense')),
                ('adsense_client_id', models.CharField(blank=True, max_length=64, verbose_name='AdSense client id (ca-pub-...)')),
                ('adsense_slot_top', models.CharField(blank=True, max_length=32, verbose_name='AdSense слот: верх (leaderboard)')),
                ('adsense_slot_sidebar', models.CharField(blank=True, max_length=32, verbose_name='AdSense слот: боковая панель')),
                ('adsense_slot_bottom', models.CharField(blank=True, max_length=32, verbose_name='AdSense слот: низ')),
                ('adsense_slot_in_content', models.CharField(blank=True, max_length=32, verbose_name='AdSense слот: в контенте')),
                ('yandex_ads_enabled', models.BooleanField(default=False, verbose_name='Включить РСЯ (Яндекс)')),
                ('yandex_block_id', models.CharField(blank=True, max_length=64, verbose_name='РСЯ: ID блока (R-A-...)')),
            ],
            options={
                'verbose_name': 'Настройки рекламы',
                'verbose_name_plural': 'Настройки рекламы',
            },
        ),
    ]
