"""
Django settings for fc26_django project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Загрузка переменных из .env (если файл есть)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _env_bool(name, default='0'):
    return os.environ.get(name, default).strip().lower() in ('1', 'true', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY') or 'django-insecure-b-3z3v0a@zh$a1gmek(#%53kfy#=^nos8^sbjks57_6y$(ut5*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', '1')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'accounts',
    'tournament',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# django-allauth
# Подтверждение email только при регистрации; при входе повторно не требуем и не отправляем письмо
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_ADAPTER = 'accounts.adapters.AccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'  # Google уже верифицирует email
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
}

# SMTP: если заданы EMAIL_HOST в .env или окружении — реальная отправка, иначе консоль
EMAIL_HOST = os.environ.get('EMAIL_HOST', '').strip()
if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes')
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@example.com')
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'fc26_django.middleware.LocaleFromIPMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fc26_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.saas_context',
                'accounts.context_processors.ads_manager',
            ],
        },
    },
]

WSGI_APPLICATION = 'fc26_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
if DATABASE_URL:
    try:
        import dj_database_url
        DATABASES = {'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600)}
    except ImportError:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
# Автоопределение языка по IP (см. middleware.LocaleFromIPMiddleware)

LANGUAGE_CODE = 'ru'

LANGUAGES = [
    ('ru', 'Русский'),
    ('en', 'English'),
    ('de', 'Deutsch'),
    ('es', 'Español'),
    ('fr', 'Français'),
    ('pt', 'Português'),
    ('uk', 'Українська'),
    ('kk', 'Қазақша'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']
LANGUAGE_COOKIE_AGE = 365 * 24 * 60 * 60  # 1 год
LANGUAGE_COOKIE_NAME = 'django_language'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 2Checkout (Кыргызстан, международные платежи). В .env: TWOCHECKOUT_SID, TWOCHECKOUT_SECRET_WORD
# TWOCHECKOUT_DEMO=1 — тестовые продажи, пока аккаунт на проверке (In review)
TWOCHECKOUT_SID = os.environ.get('TWOCHECKOUT_SID', '').strip()
TWOCHECKOUT_SECRET_WORD = os.environ.get('TWOCHECKOUT_SECRET_WORD', '').strip()
TWOCHECKOUT_DEMO = os.environ.get('TWOCHECKOUT_DEMO', '1').strip() in ('1', 'true', 'yes')
TWOCHECKOUT_CHECKOUT_URL = 'https://www.2checkout.com/checkout/purchase'

# Robokassa (СНГ). В .env: ROBOKASSA_LOGIN, ROBOKASSA_PASSWORD1, ROBOKASSA_PASSWORD2, ROBOKASSA_TEST=1
ROBOKASSA_LOGIN = os.environ.get('ROBOKASSA_LOGIN', '').strip()
ROBOKASSA_PASSWORD1 = os.environ.get('ROBOKASSA_PASSWORD1', '').strip()
ROBOKASSA_PASSWORD2 = os.environ.get('ROBOKASSA_PASSWORD2', '').strip()
ROBOKASSA_TEST = os.environ.get('ROBOKASSA_TEST', '1').strip() in ('1', 'true', 'yes')
ROBOKASSA_URL = 'https://auth.robokassa.ru/Merchant/Index.aspx'
if ROBOKASSA_TEST:
    ROBOKASSA_URL = 'https://auth.robokassa.ru/Merchant/Index.aspx'  # тест через IsTest=1

# Кэш: при REDIS_URL — Redis (общий для воркеров, Django 4.0+), иначе LocMem (dev).
REDIS_URL = os.environ.get('REDIS_URL', '').strip()
if REDIS_URL:
    try:
        import redis  # noqa: F401
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                'LOCATION': REDIS_URL,
            },
        }
    except ImportError:
        # На случай, если REDIS_URL задан, но пакет redis не установлен (например, на build-этапе)
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'OPTIONS': {'MAX_ENTRIES': 500},
            },
        }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'OPTIONS': {'MAX_ENTRIES': 500},
        },
    }

# Аналитика воронки подписки (GA4, Яндекс.Метрика). ID из .env.
GA4_MEASUREMENT_ID = os.environ.get('GA4_MEASUREMENT_ID', '').strip()  # G-XXXXXXXXXX
YANDEX_METRIKA_ID = os.environ.get('YANDEX_METRIKA_ID', '').strip()    # 12345678

# Production security (when DEBUG=False or DJANGO_ENV=production)
DJANGO_ENV = os.environ.get('DJANGO_ENV', '').strip().lower()
_is_production = not DEBUG or DJANGO_ENV == 'production'
if _is_production:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', 'true')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    if os.environ.get('SECURE_HSTS_SECONDS'):
        SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', 0))
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
