# Generated by Django 6.0.2 on 2026-03-03 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_subscription_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, verbose_name='Никнейм')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Аватар')),
                ('is_primary', models.BooleanField(default=False, help_text='Для FREE всегда один; для PRO — выбранный по умолчанию.', verbose_name='Основной профиль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Игровой профиль',
                'verbose_name_plural': 'Игровые профили',
                'ordering': ['-is_primary', 'created_at'],
                'unique_together': {('user', 'nickname')},
            },
        ),
        migrations.CreateModel(
            name='ProfileStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0, verbose_name='Матчей сыграно')),
                ('matches_won', models.PositiveIntegerField(default=0, verbose_name='Побед')),
                ('matches_lost', models.PositiveIntegerField(default=0, verbose_name='Поражений')),
                ('matches_draw', models.PositiveIntegerField(default=0, verbose_name='Ничьих')),
                ('tournaments_won', models.PositiveIntegerField(default=0, verbose_name='Турниров выиграно')),
                ('goals_scored', models.PositiveIntegerField(default=0, verbose_name='Голов забито')),
                ('goals_conceded', models.PositiveIntegerField(default=0, verbose_name='Голов пропущено')),
                ('winrate_percent', models.FloatField(default=0.0, verbose_name='Winrate %')),
                ('max_goals_per_match', models.PositiveSmallIntegerField(default=0, verbose_name='Рекорд голов за матч')),
                ('max_goals_conceded_per_match', models.PositiveSmallIntegerField(default=0, verbose_name='Антирекорд пропущенных')),
                ('most_used_team', models.CharField(blank=True, max_length=200, verbose_name='Самая частая команда')),
                ('game_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='accounts.gameprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Статистика профиля',
                'verbose_name_plural': 'Статистика профилей',
            },
        ),
    ]
