# Generated by Django 5.2.9 on 2026-03-10 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_game_profiles_and_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Бесплатный'), ('monthly', 'Месячная ($6/мес)'), ('yearly', 'Годовая ($55/год)')], max_length=20)),
                ('provider', models.CharField(choices=[('2checkout', '2Checkout'), ('robokassa', 'Robokassa')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_subscription_payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ожидающий платёж подписки',
                'verbose_name_plural': 'Ожидающие платежи подписки',
            },
        ),
    ]
